/* atmosphere.comp */
#version 460 core

uniform vec3 sunDirection;
uniform int numberOfRings;


#include <constants>
#include <sample>


layout(local_size_x=32, local_size_y=1, local_size_z=1) in;



const vec3 wavelengths = vec3(700.0f, 530.0f, 440.0f); //R/G/B wavelengths (nm)
vec3 scatteringCoefficients = vec3(
	400.0f / wavelengths.r,
	400.0f / wavelengths.g,
	400.0f / wavelengths.b
) * RAYLEIGH_STRENGTH;







#define atmosRadius (Pr + Ar)
float rayAtmosphereLength(const in vec3 origin, const in vec3 direction) {
	//Get length of ray in 3D atmosphere, from arbitrary 3D origin.
	//Guarenteed to be inside the sphere.

	float b = dot(origin, direction);
	float c = dot(origin, origin) - (atmosRadius * atmosRadius);

	float discriminant = (b*b) - c;
	if (discriminant <= 0.0f) {return 0.0f;}
	return -b + sqrt(discriminant);
}



bool rayHitsPlanet(const in vec3 origin, const in vec3 dir) {
	//Find if a ray hits the planet.
	float b = dot(origin, dir);
	float c = dot(origin, origin) - (Pr * Pr);
	float disc = (b*b) - c;

	if (disc < 0.0f) {return false;}

	float t = -b - sqrt(disc);

	return (t > 0.0f);
}



float opticalDensityAtPoint(const in vec3 point) {
	//Uses altitude to determine atmospheric density, thus optical density.
	float altitude = length(point) - Pr; //Distance from origin (centre of planet) - radius of planet = altitude.
	float altScaled = clamp(altitude / Ar, 0.0f, 1.0f);
	return exp(-altScaled * DENSITY_FALLOFF);
}



float opticalDepthAlongRay(const in vec3 origin, const in vec3 direction, const in float length) {
	//Determines optical depth of a ray from multiple samples along its length.
	float stepSize = length / float(NUM_OPTICAL_DEPTH_SAMPLES - 1u);
	vec3 densitySamplePoint = origin + direction * (0.5f * stepSize);

	float opticalDepth = 0.0f;
	for (uint i=0u; i<NUM_OPTICAL_DEPTH_SAMPLES; i++) {
		float localDensity = opticalDensityAtPoint(densitySamplePoint);
		opticalDepth += localDensity * stepSize * EXTINCTION;
		densitySamplePoint += direction * stepSize;
	}

	return opticalDepth;
}



vec3 calculateLight(const in vec3 viewDir, const in float distanceThroughAtmosphere, const in vec3 sunDirection) {
	vec3 inScatterPoint = VIEW_ORIGIN;
	float stepSize = distanceThroughAtmosphere / float(NUM_IN_SCATTER_SAMPLES - 1u);
	float mu = dot(viewDir, sunDirection);
	
	vec3 inScatteredLight = vec3(0.0f, 0.0f, 0.0f);
	for (uint i=0u; i<NUM_IN_SCATTER_SAMPLES; i++) {
		//Step through atmos _n_ times and evaluate light contrib at each sample point.
		if (rayHitsPlanet(inScatterPoint, sunDirection)) {
			inScatterPoint += viewDir * stepSize;
			continue;
		}

		float sunRayLength = rayAtmosphereLength(inScatterPoint, sunDirection);
		float sunRayOpticalDepth = opticalDepthAlongRay(inScatterPoint, sunDirection, sunRayLength);
		float viewRayOpticalDepth = opticalDepthAlongRay(inScatterPoint, -viewDir, stepSize * float(i));

		vec3 transmittance = exp(-(sunRayOpticalDepth + viewRayOpticalDepth) * scatteringCoefficients);
		float localDensity = opticalDensityAtPoint(inScatterPoint);

		float rayleighPhase = (3.0f / (16.0f * PI)) * (1.0f + mu * mu);
		vec3 rayleigh = scatteringCoefficients * rayleighPhase;

		float mieAniso2 = MIE_ANISOTROPY*MIE_ANISOTROPY;
		float mieT = 1.0f + mieAniso2 - 2.0f * MIE_ANISOTROPY * mu;
		float miePhase = (
			(
				3.0f * (1.0f - mieAniso2) * (1.0f + mu * mu)
			) /	(
				8.0f * PI * (2.0f + mieAniso2) *
				mieT * sqrt(mieT) //t^1.5
			)
		);
		vec3 mie = vec3(MIE_STRENGTH * miePhase);

		inScatteredLight += localDensity * transmittance * (rayleigh + mie) * stepSize;
		inScatterPoint += viewDir * stepSize;
	}

	return inScatteredLight;
}



vec3 calculateSkyColour(const in vec3 sampleDirection) {
	vec3 viewDir = normalize(sampleDirection);
	float sinPitch = viewDir.z; //Sin of pitch is vertical component, 0-1.

	//Camera is always on surface, at "pole" (top) of planetary sphere.
	float distanceThroughAtmosphere = (
		-(Pr*sinPitch) + sqrt(
			(Pr*Pr)*(sinPitch*sinPitch) +
			(2.0f*Pr*Ar) +
			(Ar*Ar)
		)
	);

	vec3 light = calculateLight(viewDir, distanceThroughAtmosphere, sunDirection);
	return light * EXPOSURE;
}



void main() {
	uint sampleID = gl_GlobalInvocationID.x;
	vec3 direction = samples[sampleID].direction;

	//x^4
	scatteringCoefficients *= scatteringCoefficients;
	scatteringCoefficients *= scatteringCoefficients;


	samples[sampleID].colour=calculateSkyColour(direction);
}